add a priority label
jetstack/version-checker pull request #288
Opened 2024-10-22 08:23 UTC by roelarents

In our use case we have many images and we'd like to be able to prioritize better. In order to sort by arbitrary priority, this PR adds a `priority` label (set as an annotation).

2025-01-24 09:25 UTC, davidcollom requested changes
Hi, Thanks for raising this PR and apologies for the long/late response.

I'd like to understand a little more about the use case you're depicting here, is the priority usage to be for Priority in version checking.

Or is it so that you can perform prometheus queries sorted by said label and prioritize there?

If the former, I'm not sure (as commented) if it's the right thing in exposing said priority label as this could increase cardinality and have adverse effects on upstream storage engines.

If the latter, I'd be inclined to run multiple version-checkers OR simply use `metric_relabel_configs` for those images that need a priority label defined.

2025-01-24 09:25 UTC, davidcollom commented on pkg/metrics/metrics.go
> +		"priority":        priority,
Do we need `priority` to be output as a metric label? What is the intended use case of this? I'm concerned that this could increase cardinality unnecessarily? I'd favour logging over exposing as a metrics label.

2025-01-24 09:25 UTC, davidcollom commented on pkg/metrics/metrics_test.go
If we do need this, (see comment in `metrics.go`) Can we have a test that covers the setting and reflection of a different priority and validate that the metric set reflects the value given.

2025-01-24 09:25 UTC, davidcollom commented on pkg/controller/sync.go
> +		strconv.Itoa(result.Priority),
as with `metrics.go` - I'm not entirely sure this would be needed.

2025-01-24 09:46 UTC, roelarents commented
Thx for checking!

Our use case is the latter. We have ~100 images and with prometheus/grafana we want the most important ones on top. We use priorities from zero (default) to 10. 

Regarding the extra label: a label is added, but with a stable value. That should not increase cardinality, I think. Same amount of time series.

2025-03-24 17:43 UTC, davidcollom commented
Thanks for the response, and sorry for the delay in getting back to you.

I'm not 100% sure on this one - I can see the usecase of wanting things like `grafana:latest` to be up to date and reported in your Alerts/Graphs etc... but I feel that these could be added at a later time in a more manageable and meaning way.. again similar to that of https://github.com/jetstack/version-checker/pull/296#issuecomment-2612064340

```yaml
metrics_relabel_configs:
  - source_labels: [image]
    regex: "grafana\:(.*)"
    target_label: priority
    replacement: "1000"
    action: replace
```

Similar could also be done based off namespace and any other pods/containers within the existing set of metrics exposed by version-checker without any code changes.

2025-03-25 15:27 UTC, roelarents commented
I agree [metric_relabel_configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/) could be used here. I don't know if it would be more manageable and meaningful. The config would be moved to the general prometheus config instead of the version-checker config.

2025-08-31 02:01 UTC, closed without merging