Resolve SHA256 to tags automatically if the images specified in the k8s manifests doesn't contain tag.
jetstack/version-checker pull request #70
Opened 2021-01-04 15:11 UTC by jahantech

We currently have a case where the images are resolved to sha256 digest before being added to the manifest. Which means it becomes impossible for us to resolve them back to tags with the current functionality of the version checker. These changes allow the resolution of tags from sha256 in the image field.

2021-02-10 16:22 UTC, jahantech commented
Any update on this please if this feature is acceptable? thank you

2021-02-15 17:58 UTC, JoshVanL commented
Hmm, the problem with this is that multiple tags can be assigned to the same sha. In this current implementation we are just taking the first we come across. This can be wrong _most_ of the time.

2022-08-22 17:47 UTC, JoshVanL commented on pkg/controller/checker/checker.go
> +
Should we not be doing something with the error here? At least logging it?

2022-08-22 17:49 UTC, JoshVanL commented on pkg/controller/search/search.go
> +		fmt.Println("failed to resolve the sha " + err.Error())
We never use ‘fmt.Printf’, and instead use a loft which maintains context.

I don’t think a log here is necessary anyway.

2022-08-22 17:49 UTC, JoshVanL commented on pkg/controller/search/search.go
> +		return "", fmt.Errorf("failed to resolve sha to tag")
Include err

2022-08-22 17:49 UTC, JoshVanL requested changes
Some comments from me. The approach makes sense to me!

2025-04-03 08:36 UTC, maria-reynoso approved these changes

2025-04-03 13:33 UTC, merged